/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApuracaoRouteImport } from './routes/apuracao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as ApiAnalisarRouteImport } from './routes/api/analisar'
import { Route as ApiCertificadoRouteImport } from './routes/api/certificado'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPortalAcessoRouteImport } from './routes/api/portal-acesso'
import { Route as ApiDfeBuscarRouteImport } from './routes/api/dfe.buscar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApuracaoRoute = ApuracaoRouteImport.update({
  id: '/apuracao',
  path: '/apuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalisarRoute = ApiAnalisarRouteImport.update({
  id: '/api/analisar',
  path: '/api/analisar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificadoRoute = ApiCertificadoRouteImport.update({
  id: '/api/certificado',
  path: '/api/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalAcessoRoute = ApiPortalAcessoRouteImport.update({
  id: '/api/portal-acesso',
  path: '/api/portal-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDfeBuscarRoute = ApiDfeBuscarRouteImport.update({
  id: '/api/dfe/buscar',
  path: '/api/dfe/buscar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apuracao': typeof ApuracaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta': typeof ConsultaRoute
  '/empresa': typeof EmpresaRoute
  '/entrar': typeof EntrarRoute
  '/fiscal': typeof FiscalRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/pendencias': typeof PendenciasRoute
  '/portal': typeof PortalRoute
  '/produtos': typeof ProdutosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/api/analisar': typeof ApiAnalisarRoute
  '/api/certificado': typeof ApiCertificadoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/portal-acesso': typeof ApiPortalAcessoRoute
  '/api/dfe/buscar': typeof ApiDfeBuscarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apuracao': typeof ApuracaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta': typeof ConsultaRoute
  '/empresa': typeof EmpresaRoute
  '/entrar': typeof EntrarRoute
  '/fiscal': typeof FiscalRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/pendencias': typeof PendenciasRoute
  '/portal': typeof PortalRoute
  '/produtos': typeof ProdutosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/api/analisar': typeof ApiAnalisarRoute
  '/api/certificado': typeof ApiCertificadoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/portal-acesso': typeof ApiPortalAcessoRoute
  '/api/dfe/buscar': typeof ApiDfeBuscarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apuracao': typeof ApuracaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta': typeof ConsultaRoute
  '/empresa': typeof EmpresaRoute
  '/entrar': typeof EntrarRoute
  '/fiscal': typeof FiscalRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/pendencias': typeof PendenciasRoute
  '/portal': typeof PortalRoute
  '/produtos': typeof ProdutosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/api/analisar': typeof ApiAnalisarRoute
  '/api/certificado': typeof ApiCertificadoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/portal-acesso': typeof ApiPortalAcessoRoute
  '/api/dfe/buscar': typeof ApiDfeBuscarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apuracao'
    | '/configuracoes'
    | '/consulta'
    | '/empresa'
    | '/entrar'
    | '/fiscal'
    | '/historico'
    | '/importar'
    | '/pendencias'
    | '/portal'
    | '/produtos'
    | '/redefinir-senha'
    | '/api/analisar'
    | '/api/certificado'
    | '/api/chat'
    | '/api/portal-acesso'
    | '/api/dfe/buscar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apuracao'
    | '/configuracoes'
    | '/consulta'
    | '/empresa'
    | '/entrar'
    | '/fiscal'
    | '/historico'
    | '/importar'
    | '/pendencias'
    | '/portal'
    | '/produtos'
    | '/redefinir-senha'
    | '/api/analisar'
    | '/api/certificado'
    | '/api/chat'
    | '/api/portal-acesso'
    | '/api/dfe/buscar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apuracao'
    | '/configuracoes'
    | '/consulta'
    | '/empresa'
    | '/entrar'
    | '/fiscal'
    | '/historico'
    | '/importar'
    | '/pendencias'
    | '/portal'
    | '/produtos'
    | '/redefinir-senha'
    | '/api/analisar'
    | '/api/certificado'
    | '/api/chat'
    | '/api/portal-acesso'
    | '/api/dfe/buscar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApuracaoRoute: typeof ApuracaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConsultaRoute: typeof ConsultaRoute
  EmpresaRoute: typeof EmpresaRoute
  EntrarRoute: typeof EntrarRoute
  FiscalRoute: typeof FiscalRoute
  HistoricoRoute: typeof HistoricoRoute
  ImportarRoute: typeof ImportarRoute
  PendenciasRoute: typeof PendenciasRoute
  PortalRoute: typeof PortalRoute
  ProdutosRoute: typeof ProdutosRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ApiAnalisarRoute: typeof ApiAnalisarRoute
  ApiCertificadoRoute: typeof ApiCertificadoRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPortalAcessoRoute: typeof ApiPortalAcessoRoute
  ApiDfeBuscarRoute: typeof ApiDfeBuscarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apuracao': {
      id: '/apuracao'
      path: '/apuracao'
      fullPath: '/apuracao'
      preLoaderRoute: typeof ApuracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analisar': {
      id: '/api/analisar'
      path: '/api/analisar'
      fullPath: '/api/analisar'
      preLoaderRoute: typeof ApiAnalisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificado': {
      id: '/api/certificado'
      path: '/api/certificado'
      fullPath: '/api/certificado'
      preLoaderRoute: typeof ApiCertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal-acesso': {
      id: '/api/portal-acesso'
      path: '/api/portal-acesso'
      fullPath: '/api/portal-acesso'
      preLoaderRoute: typeof ApiPortalAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dfe/buscar': {
      id: '/api/dfe/buscar'
      path: '/api/dfe/buscar'
      fullPath: '/api/dfe/buscar'
      preLoaderRoute: typeof ApiDfeBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApuracaoRoute: ApuracaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConsultaRoute: ConsultaRoute,
  EmpresaRoute: EmpresaRoute,
  EntrarRoute: EntrarRoute,
  FiscalRoute: FiscalRoute,
  HistoricoRoute: HistoricoRoute,
  ImportarRoute: ImportarRoute,
  PendenciasRoute: PendenciasRoute,
  PortalRoute: PortalRoute,
  ProdutosRoute: ProdutosRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ApiAnalisarRoute: ApiAnalisarRoute,
  ApiCertificadoRoute: ApiCertificadoRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPortalAcessoRoute: ApiPortalAcessoRoute,
  ApiDfeBuscarRoute: ApiDfeBuscarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
