/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as ApiAnalisarRouteImport } from './routes/api/analisar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalisarRoute = ApiAnalisarRouteImport.update({
  id: '/api/analisar',
  path: '/api/analisar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consulta': typeof ConsultaRoute
  '/empresa': typeof EmpresaRoute
  '/entrar': typeof EntrarRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/api/analisar': typeof ApiAnalisarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consulta': typeof ConsultaRoute
  '/empresa': typeof EmpresaRoute
  '/entrar': typeof EntrarRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/api/analisar': typeof ApiAnalisarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consulta': typeof ConsultaRoute
  '/empresa': typeof EmpresaRoute
  '/entrar': typeof EntrarRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/api/analisar': typeof ApiAnalisarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consulta'
    | '/empresa'
    | '/entrar'
    | '/historico'
    | '/importar'
    | '/api/analisar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consulta'
    | '/empresa'
    | '/entrar'
    | '/historico'
    | '/importar'
    | '/api/analisar'
  id:
    | '__root__'
    | '/'
    | '/consulta'
    | '/empresa'
    | '/entrar'
    | '/historico'
    | '/importar'
    | '/api/analisar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultaRoute: typeof ConsultaRoute
  EmpresaRoute: typeof EmpresaRoute
  EntrarRoute: typeof EntrarRoute
  HistoricoRoute: typeof HistoricoRoute
  ImportarRoute: typeof ImportarRoute
  ApiAnalisarRoute: typeof ApiAnalisarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analisar': {
      id: '/api/analisar'
      path: '/api/analisar'
      fullPath: '/api/analisar'
      preLoaderRoute: typeof ApiAnalisarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultaRoute: ConsultaRoute,
  EmpresaRoute: EmpresaRoute,
  EntrarRoute: EntrarRoute,
  HistoricoRoute: HistoricoRoute,
  ImportarRoute: ImportarRoute,
  ApiAnalisarRoute: ApiAnalisarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
